import os

os.system('pip install networkx')
os.system('pip install scikit-image')
os.system('pip install opencv-python')
os.system('pip install visdom')
os.system('pip install tensorboardX')
os.system('pip install matplotlib')
os.system('pip install seaborn')
os.system('pip install tqdm')
os.system('pip install scikit-learn')
os.system('pip install pyyaml')
os.system('pip install einops')
os.system('pip install ttach')
os.system('pip install lxml')
